### ISSUE TITLE
Primer Sequences

### ISSUE THREAD

**Issue by mcrone** [kblin/covid-spike-classification#7]
Thank you for an awesome tool. Works fantastically (using the docker container)!

Are the primer sequences that are being used publicly available? I'm currently using Thermofisher primers which cover a slightly smaller area.

**Comment by kblin** [comment]
Sure, we're using primers from the ARCTIC set. The protocol is published at https://www.protocols.io/view/sanger-sequencing-of-a-part-of-the-sars-cov-2-spik-bsbdnai6. We have submitted a preprint with some validation data as well, but I don't think that's live yet.

**Comment by tuspjo** [comment]
the preprint is online now: https://www.medrxiv.org/content/10.1101/2021.03.27.21252266v1
the protocol can be found here: https://www.protocols.io/view/sanger-sequencing-of-a-part-of-the-sars-cov-2-spik-bsbdnai6
best, 
Tue

**Comment by kblin** [comment]
Closing the issue now, but let us know if there's any questions about either the lab or the software side of this.
